//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWebClient.ReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportItem", Namespace="http://schemas.datacontract.org/2004/07/FastReport.Service")]
    [System.SerializableAttribute()]
    public partial class ReportItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path {
            get {
                return this.PathField;
            }
            set {
                if ((object.ReferenceEquals(this.PathField, value) != true)) {
                    this.PathField = value;
                    this.RaisePropertyChanged("Path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GearItem", Namespace="http://schemas.datacontract.org/2004/07/FastReport.Service")]
    [System.SerializableAttribute()]
    public partial class GearItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension {
            get {
                return this.ExtensionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionField, value) != true)) {
                    this.ExtensionField = value;
                    this.RaisePropertyChanged("Extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MimeType {
            get {
                return this.MimeTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeTypeField, value) != true)) {
                    this.MimeTypeField = value;
                    this.RaisePropertyChanged("MimeType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Properties {
            get {
                return this.PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertiesField, value) != true)) {
                    this.PropertiesField = value;
                    this.RaisePropertyChanged("Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportRequest", Namespace="http://schemas.datacontract.org/2004/07/FastReport.Service")]
    [System.SerializableAttribute()]
    public partial class ReportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFWebClient.ReportService.GearItem GearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFWebClient.ReportService.ReportItem ReportField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFWebClient.ReportService.GearItem Gear {
            get {
                return this.GearField;
            }
            set {
                if ((object.ReferenceEquals(this.GearField, value) != true)) {
                    this.GearField = value;
                    this.RaisePropertyChanged("Gear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFWebClient.ReportService.ReportItem Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IFastReportService")]
    public interface IFastReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/About", ReplyAction="http://tempuri.org/IFastReportService/AboutResponse")]
        string About();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetReportsListByPath", ReplyAction="http://tempuri.org/IFastReportService/GetReportsListByPathResponse")]
        WCFWebClient.ReportService.ReportItem[] GetReportsListByPath(string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetReportsList", ReplyAction="http://tempuri.org/IFastReportService/GetReportsListResponse")]
        WCFWebClient.ReportService.ReportItem[] GetReportsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetGearList", ReplyAction="http://tempuri.org/IFastReportService/GetGearListResponse")]
        WCFWebClient.ReportService.GearItem[] GetGearList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetReport", ReplyAction="http://tempuri.org/IFastReportService/GetReportResponse")]
        System.IO.Stream GetReport(WCFWebClient.ReportService.ReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetHTML", ReplyAction="http://tempuri.org/IFastReportService/GetHTMLResponse")]
        System.IO.Stream GetHTML(System.IO.Stream preparedReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetPDF", ReplyAction="http://tempuri.org/IFastReportService/GetPDFResponse")]
        System.IO.Stream GetPDF(System.IO.Stream preparedReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetTest", ReplyAction="http://tempuri.org/IFastReportService/GetTestResponse")]
        System.IO.Stream GetTest(System.IO.Stream preparedReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/CheckPreparedReport", ReplyAction="http://tempuri.org/IFastReportService/CheckPreparedReportResponse")]
        bool CheckPreparedReport(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/PutPreparedReport", ReplyAction="http://tempuri.org/IFastReportService/PutPreparedReportResponse")]
        string PutPreparedReport(System.IO.Stream preparedReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetPreparedByUUID", ReplyAction="http://tempuri.org/IFastReportService/GetPreparedByUUIDResponse")]
        System.IO.Stream GetPreparedByUUID(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetHTMLByUUID", ReplyAction="http://tempuri.org/IFastReportService/GetHTMLByUUIDResponse")]
        System.IO.Stream GetHTMLByUUID(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetPDFByUUID", ReplyAction="http://tempuri.org/IFastReportService/GetPDFByUUIDResponse")]
        System.IO.Stream GetPDFByUUID(string uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetLogoByUUID", ReplyAction="http://tempuri.org/IFastReportService/GetLogoByUUIDResponse")]
        System.IO.Stream GetLogoByUUID(string uuid, string width, string height);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFastReportService/GetLogoByUUIDFixed", ReplyAction="http://tempuri.org/IFastReportService/GetLogoByUUIDFixedResponse")]
        System.IO.Stream GetLogoByUUIDFixed(string uuid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFastReportServiceChannel : WCFWebClient.ReportService.IFastReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FastReportServiceClient : System.ServiceModel.ClientBase<WCFWebClient.ReportService.IFastReportService>, WCFWebClient.ReportService.IFastReportService {
        
        public FastReportServiceClient() {
        }
        
        public FastReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FastReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FastReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string About() {
            return base.Channel.About();
        }
        
        public WCFWebClient.ReportService.ReportItem[] GetReportsListByPath(string path) {
            return base.Channel.GetReportsListByPath(path);
        }
        
        public WCFWebClient.ReportService.ReportItem[] GetReportsList() {
            return base.Channel.GetReportsList();
        }
        
        public WCFWebClient.ReportService.GearItem[] GetGearList() {
            return base.Channel.GetGearList();
        }
        
        public System.IO.Stream GetReport(WCFWebClient.ReportService.ReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public System.IO.Stream GetHTML(System.IO.Stream preparedReport) {
            return base.Channel.GetHTML(preparedReport);
        }
        
        public System.IO.Stream GetPDF(System.IO.Stream preparedReport) {
            return base.Channel.GetPDF(preparedReport);
        }
        
        public System.IO.Stream GetTest(System.IO.Stream preparedReport) {
            return base.Channel.GetTest(preparedReport);
        }
        
        public bool CheckPreparedReport(string uuid) {
            return base.Channel.CheckPreparedReport(uuid);
        }
        
        public string PutPreparedReport(System.IO.Stream preparedReport) {
            return base.Channel.PutPreparedReport(preparedReport);
        }
        
        public System.IO.Stream GetPreparedByUUID(string uuid) {
            return base.Channel.GetPreparedByUUID(uuid);
        }
        
        public System.IO.Stream GetHTMLByUUID(string uuid) {
            return base.Channel.GetHTMLByUUID(uuid);
        }
        
        public System.IO.Stream GetPDFByUUID(string uuid) {
            return base.Channel.GetPDFByUUID(uuid);
        }
        
        public System.IO.Stream GetLogoByUUID(string uuid, string width, string height) {
            return base.Channel.GetLogoByUUID(uuid, width, height);
        }
        
        public System.IO.Stream GetLogoByUUIDFixed(string uuid) {
            return base.Channel.GetLogoByUUIDFixed(uuid);
        }
    }
}
